version: "3.6"

services:

  gimp:

    volumes:
      - ./wordpress/gimp/:/gimp/

  wordpress:

    volumes:
      - ./wordpress/plugin:/var/www/html/wp-content/plugins/varilink-site-plugin
      - ./wordpress/theme:/var/www/html/wp-content/themes/varilink-site-theme

  wp-cli:

    volumes:
      - ./wordpress/plugin:/var/www/html/wp-content/plugins/varilink-site-plugin
      - ./wordpress/theme:/var/www/html/wp-content/themes/varilink-site-theme
